
# limbus-buildgen - A "build anywhere" C/C++ makefile/project generator.
# Written in 2014-2016 by Jesper Oskarsson jesosk@gmail.com
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain worldwide.
# This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

env:
  node: true
  browser: true
extends: 'eslint:recommended'
rules:
  accessor-pairs:
    - error
    - getWithoutSet: false
      setWithoutGet: false
  array-bracket-spacing: error
  array-callback-return: error
  arrow-body-style: error
  arrow-parens: error
  arrow-spacing: error
  block-scoped-var: error
  block-spacing: error
  brace-style: error
  callback-return: error
  camelcase: error
  comma-dangle:
    - error
    - only-multiline
  comma-spacing: error
  comma-style:
    - error
    - last
  complexity: error
  computed-property-spacing:
    - error
    - never
  consistent-return: error
  consistent-this: error
  curly: error
  default-case: error
  dot-location:
    - error
    - property
  dot-notation: error
  eol-last: error
  eqeqeq: error
  func-names: 'off'
  func-style: error
  generator-star-spacing: error
  global-require: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-length: error
  id-match: error
  indent: error
  init-declarations: error
  jsx-quotes: error
  key-spacing: error
  keyword-spacing: error
  linebreak-style:
    - error
    - unix
  lines-around-comment: error
  max-depth: error
  max-len: 'off'
  max-nested-callbacks: error
  max-params: error
  max-statements: 'off'
  max-statements-per-line: 'off'
  new-parens: error
  newline-after-var: 'off'
  newline-before-return: 'off'
  newline-per-chained-call: 'off'
  no-alert: 'off'
  no-array-constructor: error
  no-bitwise: 'off'
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: error
  no-console: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: 'off'
  no-empty-function: 'off'
  no-eq-null: 'off'
  no-eval:
    - error
    - allowIndirect: true
  no-extend-native: 'off'
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: 'off'
  no-floating-decimal: error
  no-implicit-globals: 'off'
  no-implied-eval: 'off'
  no-inline-comments: 'off'
  no-inner-declarations:
    - error
    - functions
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-magic-numbers: 'off'
  no-mixed-requires: error
  no-multi-spaces: 'off'
  no-multi-str: error
  no-multiple-empty-lines: error
  no-native-reassign: error
  no-negated-condition: 'off'
  no-nested-ternary: error
  no-new: error
  no-new-func: 'off'
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: 'off'
  no-path-concat: 'off'
  no-plusplus: error
  no-process-env: error
  no-process-exit: error
  no-proto: error
  no-prototype-builtins: 'off'
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-syntax: error
  no-return-assign: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: 'off'
  no-shadow-restricted-names: error
  no-spaced-func: 'off'
  no-sync: 'off'
  no-ternary: 'off'
  no-throw-literal: error
  no-trailing-spaces: 'off'
  no-undef-init: error
  no-undefined: 'off'
  no-underscore-dangle: 'off'
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unsafe-finally: error
  no-unused-expressions: 'off'
  no-use-before-define: 'off'
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-escape: error
  no-useless-rename: error
  no-var: 'off'
  no-void: error
  no-warning-comments: 'off'
  no-whitespace-before-property: error
  no-with: error
  object-curly-spacing: 'off'
  object-property-newline: 'off'
  object-shorthand: 'off'
  one-var: 'off'
  one-var-declaration-per-line: 'off'
  operator-assignment:
    - error
    - always
  operator-linebreak: 'off'
  padded-blocks: 'off'
  prefer-arrow-callback: 'off'
  prefer-const: error
  prefer-reflect: 'off'
  prefer-rest-params: 'off'
  prefer-spread: 'off'
  prefer-template: 'off'
  quote-props: 'off'
  quotes: 'off'
  radix: error
  require-jsdoc: 'off'
  require-yield: error
  semi: 'off'
  semi-spacing: 'off'
  sort-imports: error
  sort-vars: 'off'
  space-before-blocks: 'off'
  space-before-function-paren: 'off'
  space-in-parens:
    - error
    - never
  space-infix-ops: error
  space-unary-ops: error
  spaced-comment: error
  strict:
    - error
    - never
  template-curly-spacing: error
  unicode-bom:
    - error
    - never
  valid-jsdoc: 'off'
  vars-on-top: 'off'
  wrap-regex: error
  yield-star-spacing: error
  yoda:
    - error
    - never
