
# limbus-buildgen - A "build anywhere" C/C++ makefile/project generator.
# Written in 2014 by Jesper Oskarsson jesosk@gmail.com
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain worldwide.
# This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

language: c
os:
  - linux
  - osx
env:
  - BUILDGEN_NODE_VERSION="4.4.0"
  - BUILDGEN_NODE_VERSION="5.9.0"

before_install: . ./utility-scripts/install_node.sh $BUILDGEN_NODE_VERSION && nvm --version && node -v && npm -v
install: npm install
script: make && npm test && npm run coverage-travis-ci
after_script: npm run coverage-coveralls-io
