
# limbus-buildgen - A "build anywhere" C/C++ makefile/project generator.
# Written in 2014 by Jesper Oskarsson jesosk@gmail.com
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain worldwide.
# This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

install: npm install -g mocha && npm install
language: node_js
node_js:
    - "0.10"
    - "0.11"
script: make && npm test && npm run-script coverage-travis-ci && npm run-script coverage-coveralls-io

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8384dd5845e96940ca79
    on_success: change
    on_failure: always
    on_start: false
