
# limbus-buildgen - A "build anywhere" C/C++ makefile/project generator.
# Written in 2014 by Jesper Oskarsson jesosk@gmail.com
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain worldwide.
# This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

language: c
os:
  - linux
  - osx
env:
  - BUILDGEN_NODE_VERSION="4.4.0" BUILDGEN_TARGET_COMPILER="clang"
  - BUILDGEN_NODE_VERSION="5.9.0" BUILDGEN_TARGET_COMPILER="clang"
  - BUILDGEN_NODE_VERSION="4.4.0" BUILDGEN_TARGET_COMPILER="gcc"
  - BUILDGEN_NODE_VERSION="5.9.0" BUILDGEN_TARGET_COMPILER="gcc"

before_install: . utility-scripts/install_node.sh $BUILDGEN_NODE_VERSION ; brew tap homebrew/versions ; brew update > /dev/null ; brew install homebrew/versions/gcc6 ; . utility-scripts/echo-versions.sh
install: npm install ; dependencies/fetch_dependencies.sh
script: make -f Makefile.`uname -s | tr 'A-Z' 'a-z'`-$BUILDGEN_TARGET_COMPILER && npm run test -- -t 20000 && npm run coverage-travis-ci
after_script: npm run coverage-coveralls-io
