
# limbus-buildgen - A "build anywhere" C/C++ makefile/project generator.
# Written in 2014 by Jesper Oskarsson jesosk@gmail.com
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain worldwide.
# This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

version: 0.2.0+{build}

install:
    - ps: Install-Product node $env:BUILDGEN_NODE_VERSION
    - npm --version
    - npm install

build_script:
    - npm test

environment:
    matrix:
          # AppVeyor does not seem to have 5.9.0 yet.
        - BUILDGEN_NODE_VERSION: 4.4.0
          BUILDGEN_TARGET_COMPILER: cl

matrix:
    fast_finish: true
