
# limbus-buildgen - A "build anywhere" C/C++ makefile/project generator.
# Written in 2014 by Jesper Oskarsson jesosk@gmail.com
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain worldwide.
# This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

version: 0.2.0+{build}

install:
    - ps: Install-Product node 4.4
    - npm --version
    - npm install

build_script:
    - npm test

environment:
    matrix:
        - BUILDGEN_TARGET_COMPILER: cl
          BUILDGEN_TARGET_ARCHITECTURE: x86
        - BUILDGEN_TARGET_COMPILER: cl
          BUILDGEN_TARGET_ARCHITECTURE: x64

matrix:
    fast_finish: true
