all:
	gcc -c dependencies/duktape-1.4.0/src/duktape.c -o dependencies/duktape-1.4.0/src/duktape.c.o -Idependencies/duktape-1.4.0/src/ -g -O0 --coverage
	gcc -c source/duk.c -o source/duk.c.o -Idependencies/duktape-1.4.0/src/ -g -O0 --coverage
	gcc -c source/platform.c -o source/platform.c.o -Idependencies/duktape-1.4.0/src/ -g -O0 --coverage
	gcc -o limbus-buildgen dependencies/duktape-1.4.0/src/duktape.c.o source/duk.c.o source/platform.c.o  -L./ -lm
