
@echo off

REM Tries to set up development environment starting with the latest visual studio
REM down to the oldest Windows SDK

REM Passes any arguments to the actual implementations.

((call "C:\Program Files (x86)\Microsoft Visual Studio 16.0\Common7\Tools\VsDevCmd.bat" %* 2>NUL) && echo Using Visual Studio 16.0) || ((call "C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\Tools\VsDevCmd.bat" %* 2>NUL) && echo Using Visual Studio 15.0) || ((call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat" %* 2>NUL) && echo Using Visual Studio 14.0) || ((call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\VsDevCmd.bat" %* 2>NUL) && echo Using Visual Studio 12.0) || ((call "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\vsvars32.bat" %* 2>NUL) && echo Using Visual Studio 11.0) || ((call "C:\Program Files\Microsoft Visual Studio 10.0\VC\vcvarsall.bat" %* 2>NUL) && echo Using Visual Studio 10.0) || ((call "C:\Program Files\Microsoft Visual Studio 9.0\VC\vcvarsall.bat" %* 2>NUL) && echo Using Visual Studio 9.0) || ((call "C:\Program Files\Microsoft SDKs\Windows\v12.1\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 12.1) || ((call "C:\Program Files\Microsoft SDKs\Windows\v12\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 12) || ((call "C:\Program Files\Microsoft SDKs\Windows\v11.1\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 11.1) || ((call "C:\Program Files\Microsoft SDKs\Windows\v11\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 11) || ((call "C:\Program Files\Microsoft SDKs\Windows\v10.1\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 10.1) || ((call "C:\Program Files\Microsoft SDKs\Windows\v10\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 10) || ((call "C:\Program Files\Microsoft SDKs\Windows\v8.1\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 8.1) || ((call "C:\Program Files\Microsoft SDKs\Windows\v8.0\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 8.0) || ((call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 7.1) || ((call "C:\Program Files\Microsoft SDKs\Windows\v7.0\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 7.0) || ((call "C:\Program Files\Microsoft SDKs\Windows\v6.1\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 6.1) || ((call "C:\Program Files\Microsoft SDKs\Windows\v6.0\Bin\SetEnv.cmd" %* 2>NUL) && echo Using Windows SDK 6.0)
